services:
  users:
    build:
      context: .
      dockerfile: kunai_users/Dockerfile
    ports:
      - "${USER_APP_PORT}:${USER_APP_PORT}"
    command: uvicorn main:app --host 0.0.0.0 --port ${USER_APP_PORT}
    env_file:
      - .env
